Replace itsdangerous with authlib for JWS
svintit/flask-oidc-ext pull request #18
Opened 2022-10-28 09:38 UTC by bensta

itsdangerous deprecated their JWS functionality with version 2.0. Support was dropped in 2.1
Recent Apache Airflow versions depend on a newer itsdangerous version. 

This commit replaces itsdangerous dependency with authlib as recommended by itsdangerous. This makes it compatible with more recent Apache Airflow versions. 

Changes:
1. Replace serialization and deserialization with corresponding authlib functions
2. Adapt class variables to store serializer, algorithm and secret separately
3. Adapt exception handling to handle authlib exceptions
4. Pin Flask dependency to version greater 2.0.0 (1.x not supported, dependency conflict with Jinja)

For (4), check: https://stackoverflow.com/questions/71718167/importerror-cannot-import-name-escape-from-jinja2

2022-10-28 09:42 UTC, bensta commented
@svintit I hope this is useful. Please review the code carefully as it is quite relevant for security of the module. 
Also, feel free to suggest changes, particularly regarding how the serializer, secret key and singing algorithm are handled/partially hard coded in the class.

2022-11-02 12:25 UTC, svintit requested changes
This looks really good, nice work! Just a few suggestions, nothing major.

Once everything is cleaned up, i'll do a release.

2022-11-02 12:25 UTC, svintit commented on flask_oidc_ext/__init__.py
> +        self.signing_algorithm="HS256"
Seeing that we only using this in the same dict each time, let's just create the dict here to clean it up a tiny bit.
```suggestion
        self.signing_algorithm={"alg": "HS256"}
```

2022-11-02 12:25 UTC, svintit commented on flask_oidc_ext/__init__.py
> +                signed_id_token = self.cookie_serializer.serialize_compact({'alg': self.signing_algorithm}, json.dumps(g.oidc_id_token), self.secret).decode("utf-8")
```suggestion
                signed_id_token = self.cookie_serializer.serialize_compact(self.signing_algorithm, json.dumps(g.oidc_id_token), self.secret).decode("utf-8")
```

2022-11-02 12:25 UTC, svintit commented on flask_oidc_ext/__init__.py
> +        state[statefield] = self.extra_data_serializer.serialize_compact({'alg': self.signing_algorithm}, statevalue, self.secret).decode("utf-8")
```suggestion
        state[statefield] = self.extra_data_serializer.serialize_compact(self.signing_algorithm, statevalue, self.secret).decode("utf-8")
```

2022-11-02 12:25 UTC, svintit commented on flask_oidc_ext/__init__.py
> +            logger.info("Error checkin ID token signature", exc_info=True)
```suggestion
            logger.info("Error checking ID token signature", exc_info=True)
```

2023-03-02 15:22 UTC, merged